config/routes.rb
Rails.application.routes.draw do

  resources :users do 
    member do 
      get :following, :followers
    end
  end

  get 'messages/:user_id' => 'messages#show', as: :chat
  post 'messages/:user_id' => 'messages#send_message', as: :send_message  

  resources :account_activations, only: [:edit]
  resources :password_reset,      only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy] do
    resources :likes,             only: [:create, :destroy]
    resources :comments,          only: [:create, :destroy]
  end

  resources :relationships,       only: [:create, :destroy]
  
  root 'static_pages#home'
  
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new' 
  get  'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

require 'carrierwave/orm/activerecord'

  has_many :sent_messages, class_name: "Message", foreign_key: :sender_id
  has_many :received_messages, class_name: "Message", foreign_key: :recipient_id

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: :follower_id,
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: :followed_id,
                                  dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  attr_accessor :remember_token, :activation_token, :reset_token

  has_secure_password

  before_save :downcase_email
  before_create :create_activation_digest

  mount_uploader :avatar, AvatarUploader
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255}, 
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :checkbox, presence: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ?
    BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end 

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end  

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # def feed
  #   Micropost.where("user_id = ?", id)
  # end


  def follow(user)
    active_relationships.create(followed_id: user.id)
  end
  
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                      WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                    OR user_id = :user_id", user_id: id)
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update, :index, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]

  def index
    @users = User.paginate(page: params[:page])
  end  

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end  

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check ur email bro to activate your account."
      redirect_to root_url
    else 
      render 'new'
    end 
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Fuck yeah! Successfully updated!"
      redirect_to @user
    else
      render 'edit' 
    end 
  end  

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Bye bro!"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
      :password_confirmation, :checkbox, :avatar, :user_info)
    end  

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end  

end

app/helpers/users_helper.rb
module UsersHelper
  # def gravatar_for(user)
  #   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  #   gravatar_url = "https://images.pexels.com/photos/1509534/pexels-photo-1509534.jpeg?cs=srgb&dl=pexels-steve-johnson-1509534.jpg&fm=jpg"
  #   image_tag(gravatar_url, alt: user.name, class: "gravatar", size: 70)
  # end

end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
<div><%= hidden_field_tag :followed_id, user.id %></div>
<%= f.submit "Follow", class: "btn btn-info" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(user) %>
  <div id="follow_form">
    <% if current_user.following?(user) %>
      <%= render 'unfollow', user: user %>
    <% else %>
      <%= render 'follow', user: user %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
html: { method: :delete }) do |f| %>
<%= f.submit "Unfollow", class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="people-nearby">
              
              <div class="nearby-user">
                <div class="row">
                  <div class="col-md-2 col-sm-2">
                    <% if user.avatar? %>
                    <%= image_tag user.avatar.url(:thumb), class: "profile-photo-lg", alt: "user" %>
                    <% else %>
                      <img src="/assets/default_avatar.jpg" class="profile-photo-lg">
                    <% end %>
                  </div>
                  <div class="col-md-7 col-sm-7">
                    <h4><%= link_to user.name, user %></h4>
                    <b><%= "Mood: #{user.user_info}" if user.user_info %></b>
                    <%= link_to "Chat", chat_path(user_id: user.id)%>
                    <% if current_user.admin? && !current_user?(user) %>
                    <h6>
                      <%= link_to "delete profile", user, method: :delete, class: "text-muted", data: { confirm: "You sure?" } %>
                      <% end %>
                    </h6>
                  </div>
                  <div class="col-md-3 col-sm-3">
                     <%= render 'follow_form', user: user %>
                  </div>
                </div>
              </div>

            </div>
      </div>
  </div>
</div>

app/views/users/_user1.html.erb
<li>
  <%= image_tag user.avatar.url(:thumb), class: "img-show" if user.avatar? %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
| <%= link_to "delete", user, method: :delete,
data: { confirm: "You sure?" } %>
<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="text-center" style="padding:50px 15">
    <h4>Edit ur profile here!</h4>
    <h1><%= image_tag @user.avatar.url(:thumb), class: "profile-photo-lg" if @user.avatar? %></h1>
    <div class="logo"></div>
	</br>
    <div class="login-form-1">        
        <%= form_for(@user, method: :patch, html: {multipart: true}) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
            <div class="main-login-form">
                <div class="login-group">
                    <div class="form-group">
                        <%= f.label :name, class: "sr-only" %>
                        <%= f.text_field :name, class: 'form-control', placeholder: "bro-name:" %>
                    </div>
                    <div class="form-group">
                        <%= f.label :email, class: "sr-only"  %>
			            <%= f.email_field :email, class: 'form-control', placeholder: "bro-mail:" %>
                    </div>
                    <div class="form-group">
						<%= f.label :password, class: "sr-only"%>
						<%= f.password_field :password, class: 'form-control', placeholder: "password:" %>
                    </div>
                    <div class="form-group">
                        <%= f.label :password_confirmation, "Confirmation", class: "sr-only" %>
						<%= f.password_field :password_confirmation, class: 'form-control', placeholder: "pass confirm:" %>
                    </div>
                    <div class="form-group">
                        <%= f.label :user_info, "Confirmation", class: "sr-only" %>
                        <%= f.text_field :user_info, class: 'form-control', placeholder: "mood:" %>
                    </div>
                </div>
            	</br>
            	</br>
                <%= f.file_field :avatar, class: "form-control" %>
            	<%= f.submit "Save changes", class: "btn btn-info" %>
            </div>

        <% end %>
    </div>
</div>

app/views/users/edit1.html.erb
<% provide(:title, "Edit user") %>
<div class="text-center" style="padding:50px 15">
    <h4>Edit ur profile here!</h4>
    <div class="logo"></div></br>
    <!-- Main Form -->
    <div class="login-form-1">
        <%= render 'shared/error_messages' %>
        <form class="edit_user" id="edit_user_1" action="/users/1" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="8zU-W1fd_TUSwYhkFeVXjo4NUuwx4Xy9NW_YTLPvyVV8jH9nmdp-GOjxX5eXVOj3PUv79hAruu-r3MjPHTgzHQ">
            <input name="_method" type="hidden" value="patch" />
            <div class="login-form-main-message"></div>
            <div class="main-login-form">
                <div class="login-group">

                    <div class="form-group">
                        <label for="user_name" class="sr-only">Name</label>
                        <input type="text" class="form-control" id="user_name" name="user[name]" placeholder="bro-name:">
                    </div>
                    <div class="form-group">
                        <label for="user-email" class="sr-only">Email</label>
                        <input type="email" class="form-control" id="user_email" name="user[email]" placeholder="bro-mail:">
                    </div>
                    <div class="form-group">
                        <label for="user_password" class="sr-only">Password</label>
                        <input type="password" class="form-control" id="user_password" name="user[password]" placeholder="password:">
                    </div>
                    
                    <div class="form-group">
                        <label for="user_password_confirmation" class="sr-only">Password Confirm</label>
                        <input type="password" class="form-control" id="user_password_confirmation" name="user[password_confirmation]" placeholder="pass confirm:">
                    </div>
                    

                </div></br></br>
             <input type="submit" name="commit" value="save changes" class="btn btn-info" data-disable-with="Save changes">
            </div>
        </form>
    </div>
    <!-- end:Main Form -->
</div>


    <div class="gravatar_edit">
        <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target="_blank">change</a>

app/views/users/index.html.erb
<% provide(:title, 'All bros') %>

<h2>Here is all brothers page!</h2>

<%= will_paginate %>
<ul class="users">
    <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<div class="text-center" style="padding:50px 15">
    <h4>Sign up, bro!</h4>
    <div class="logo"></div></br>
    <div class="login-form-1">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="login-form-main-message"></div>
            <div class="main-login-form">
                <div class="login-group">
                    <div class="form-group">
                        <%= f.label :name, class: "sr-only" %>
                        <%= f.text_field :name, class: 'form-control', placeholder: "bro-name" %>
                    </div>
                    <div class="form-group">
                        <%= f.label :email, class: "sr-only"  %>
                        <%= f.email_field :email, class: 'form-control', placeholder: "bro-mail:" %>
                    </div>
                    <div class="form-group">
                        <%= f.label :password, class: "sr-only"%>
                        <%= f.password_field :password, class: 'form-control', placeholder: "password:" %>
                    </div>
                    
                    <div class="form-group">
                        <%= f.label :password_confirmation, "Confirmation", class: "sr-only" %>
                        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "pass confirm:" %>
                    </div>
                    
                    <div class="form-check">
                        <%= f.check_box :checkbox, id: 'session_remember_me' %>
                        <%= f.label :session_remember_me, "Want to become a bro!" %>
                    </div>
                </div>
                </br>
                </br>
                <%= f.submit "Become a bro!", class: "btn btn-info" %>
            </div>
            <div class="etc-login-form"></br>
                <p>Already bro?? <%= link_to "Login here", login_path %></p>
            </div>
        <% end %>
    </div>
</div>

app/views/users/new3.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up, bro!</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= f.label :name, "Bro-name:" %>
        <%= f.text_field :name %>
        <%= f.label :email, "Bro-mail:" %>
        <%= f.email_field :email %>
        <%= f.label :password, "Password:"%>
        <%= f.password_field :password %>
        <%= f.label :password_confirmation, "Confirmation:" %>
        <%= f.password_field :password_confirmation %>
        <%= f.submit "Tap here to become a bro!", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  

app/views/users/show.html.erb

<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <% if @user.avatar? %>
          <%= image_tag @user.avatar.url(:thumb), class: "profile-photo-lg"  %>
        <% else %>
          <img src="/assets/default_avatar.jpg" class="profile-photo-lg">
        <% end %>
        <%= @user.name %>
      </h1>
      <b><%= @user.user_info if @user.user_info %></b>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <section class="stats">
      <%= render 'follow_form', user: @user %>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h4>You have <%= @user.microposts.count %> posts:</h4>
      <ol class="microposts">
        <%= render @microposts %>
     </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
<aside class="col-md-4">
  <section class="user_info">
    <%= image_tag @user.avatar.url(:thumb), class: "profile-photo-lg" if @user.avatar? %>
    <h1><%= @user.name %></h1>
    <span><%= link_to "view my profile", @user %></span>
    <span><b>Microposts:</b> <%= @user.microposts.count %></span>
  </section>
  <section class="stats">
    <%= render 'shared/stats' %>
    <% if @users.any? %>
      <div class="user_avatars">
      <% @users.each do |user| %>
      <%= image_tag user.avatar.url(:thumb), class: "profile-photo-lg" if user.avatar? %>
    <% end %>
    </div>
    <% end %>
  </section>
</aside>
<div class="col-md-8">
  <h3><%= @title %></h3>
  <% if @users.any? %>
    <ul class="users follow">
      <%= render @users %>
    </ul>
    <%= will_paginate %>
  <% end %>
</div>
</div>