config/routes.rb
Rails.application.routes.draw do

  resources :users do 
    member do 
      get :following, :followers
    end
  end

  get 'messages/:user_id' => 'messages#show', as: :chat
  post 'messages/:user_id' => 'messages#send_message', as: :send_message  

  resources :account_activations, only: [:edit]
  resources :password_reset,      only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy] do
    resources :likes,             only: [:create, :destroy]
    resources :comments,          only: [:create, :destroy]
  end

  resources :relationships,       only: [:create, :destroy]
  
  root 'static_pages#home'
  
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new' 
  get  'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_comment_form.html.erb
<%= form_for(Comment.new, url: micropost_comments_path(micropost_id: micropost.id)) do |f| %>
  <div class="field">
  	<%= f.text_field :content, placeholder: "Comment, bro !", class: "form-control" %>
  </div>
    <%= f.submit "Comment !", class: "btn btn-info btn-xs" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
The form contains <%= pluralize(object.errors.count, "error") %>.
</div>
<ul>
<% object.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_like_avatar.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <div class="widget">
                <div class="widget-content">
                    <ul class="widget-user-list">
                    	<% micropost.likes.each do |like| %>
                      		<% if like.user.avatar? %>
                      			<li><a><%= image_tag like.user.avatar.url %></a></li>
                      		<% else %>	
                      			<li><a><img src="/assets/default_avatar.jpg"></a></li>
                          	<% end %>
                        <% end %>
                        <li class="number"><a><%= micropost.likes.count %></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: {multipart: true}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  	<%= f.text_field :content, placeholder: "Tell us, bro!", class: "form-control" %>
  </div>
  <div class="login-form-1">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: "form-control" %>
  </div>
  <%= f.submit "Post", class: "btn btn-info" %>
<% end %>

<script type="text/javascript">
$('#micropost_picture').bind('change', function() {
size_in_megabytes = this.files[0].size/1024/1024;
if (size_in_megabytes > 5) {
alert('Maximum file size is 5MB. Please choose a smaller file.');
}
});
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<% if current_user.avatar? %>
	<%= image_tag current_user.avatar.url(:thumb), class: "profile-photo-lg", alt: "user" %>
<% else %>
  <img src="/assets/default_avatar.jpg" width="200" height="170" style="float:initial">
<% end %>

<h4><%= current_user.name %></h4>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>
<h4><%= current_user.user_info if current_user.user_info %></h4>